### ISSUE TITLE
TOS or Privacy Policy

### ISSUE THREAD

**Issue by bowarmbold** [psocha/HomeworkTrackerExtension#1]
Is there a Terms of Service or Privacy Policy we can approve for our students? 

Thanks,

**Comment by psocha** [comment]
Hi,

The Homework Tracker Chrome extension is a small hobby app that I wrote when I was a college student. I posted the extension and its source code online with no restrictions or guarantees. As the project's lone maintainer, I am unable and unwilling to enter any arrangement where there's an element of legal compliance or legal liability involved.

In case you're wondering from a technical perspective, the data that users enter into the extension is stored in the Chrome browser's local file storage. User input is never transmitted over the internet and never replicated to any other location.

Sorry I couldn't be more help.

Peter
